CREATE TABLE history_game (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season INT NOT NULL UNIQUE CHECK (season >= 0),
  history TEXT NOT NULL,
  city_id BIGINT NOT NULL,
  CONSTRAINT fk_history_game_city FOREIGN KEY (city_id) REFERENCES city (id)
);