CREATE TABLE characters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  age INT NOT NULL CHECK (age >= 0),
  biography TEXT NOT NULL,
  users_id BIGINT,
  clans_id BIGINT,
  history_id BIGINT NOT NULL,
  city_id BIGINT NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  CONSTRAINT fk_character_users FOREIGN KEY (users_id) REFERENCES users (id),
  CONSTRAINT fk_character_clans FOREIGN KEY (clans_id) REFERENCES clans (id),
  CONSTRAINT fk_character_historygame FOREIGN KEY (history_id) REFERENCES history_game (id),
  CONSTRAINT fk_character_city FOREIGN KEY (city_id) REFERENCES city (id)
);

CREATE TABLE character_skills (
  character_id BIGINT NOT NULL,
  skills_id BIGINT NOT NULL,
  PRIMARY KEY (character_id, skills_id),
  CONSTRAINT fk_character_skills_character FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE,
  CONSTRAINT fk_character_skills_skill FOREIGN KEY (skills_id) REFERENCES skill (id) ON DELETE CASCADE
);