CREATE TABLE weapon (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_weapon VARCHAR(120) NOT NULL UNIQUE,
  power_damage INT NOT NULL CHECK (power_damage >= 1),
  required_level INT NOT NULL CHECK (required_level >= 0),
  difficulty_learning INT NOT NULL CHECK (difficulty_learning >= 0),
  character_id BIGINT,
  CONSTRAINT fk_weapon FOREIGN KEY (character_id) REFERENCES characters (id)
);